apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: builduser
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000
  type: LoadBalancer